# This is a basic workflow to help you get started with Actions

name: Postman Tasks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  
  work_flows:        
 # Allows you to run this workflow manually from the Actions tab
    
 run-postman-test:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
     # Allows you to run this workflow manually from the Actions tab
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Repo Checkout
        uses: action\checkout@v4

      # Runs a set of commands using the runners shell
      - name: Setup Node
        uses: action\setup-node@v4
        with:
            node-version: = '18'
            
            name: install newman
            run: npm install -g newman
           
            name: run postman tasks
            run: newman postman\Books.postman_collection.json -e postman\test.postman_environment.json
            
        


        